language: python
branches:
  only:
  - source
env:
  global:
  - secure: "eyjYVX3ekaozIYnS60fc8GOUj8BqT4mK05FqwPhpytJUjDQWbemG4o2E2qAs3skarl2zx0zgk77cwkPJjiLfvkMsYpIaoGiZnMa5PqK7M6uYlKB4l6qMrzjk9O7FkVb4X9xvIGSdPApJrTr/B6thsQZAbZP2GpZh28hl7rgx2ZjNzFqAazXcX27wdQAzRNVEn1XpTCNzV76GGHp/tGX3xNfitCukt5BRTNKWu8dMaX+AaE0Wygar7OrFqGbUSBAdjaM76w99ryx3AFgvfXjdXywsrRjSvCjsLsG7spHg2fkJwb1TbANq22DK/sfDzgneMMgjd6j/6437iMA1kuULs9GVjCvC7gkDLHixdwEhG1aC9kfYlwvo9qXoNqfS0YvnDfrZNLlw4cgtePSnvvf57DJVUEn+WC4wyb3bOFtU7r+svSzNmxWrI1csOly3kPZFr3R7rC9lceWgw9q9ESTCjFNgIuK/g+uVTsovBMdFUnLmJFzmX7EqBiLout68gN1pdSj86zyiBbDzZNP1+tzjUrfmHpiB+nTgEgpu6+H9XxJWWBBwiOJ/NcbvdmFTN8MZfvASWLXh+sXGpFEobHyMfRrOYW28u6v7WWeyIdW4NUV3NI5L4uEEUAQVk5F+luHbZysLx2Se1E4ndrBy+JABE6ph+pVpcnUBo8JZoCWKlHE="
install:
- pip install pelican 
- pip install ghp-import
- pip install markdown
script:
- make publish 
- 'make github 2> /dev/null'
